/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Sistema ORIGINAL Tailwind para Landing
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        // Sistema HSL para Tool (via CSS variables)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          border: "hsl(var(--sidebar-border))",
          active: "hsl(var(--sidebar-active))",
          'active-foreground': "hsl(var(--sidebar-active-foreground))",
        },
        entity: {
          person: "hsl(var(--entity-person))",
          'person-bg': "hsl(var(--entity-person-bg))",
          dni: "hsl(var(--entity-dni))",
          'dni-bg': "hsl(var(--entity-dni-bg))",
          passport: "hsl(var(--entity-passport))",
          'passport-bg': "hsl(var(--entity-passport-bg))",
          organization: "hsl(var(--entity-organization))",
          'organization-bg': "hsl(var(--entity-organization-bg))",
          cif: "hsl(var(--entity-cif))",
          'cif-bg': "hsl(var(--entity-cif-bg))",
          address: "hsl(var(--entity-address))",
          'address-bg': "hsl(var(--entity-address-bg))",
          location: "hsl(var(--entity-location))",
          'location-bg': "hsl(var(--entity-location-bg))",
          postal: "hsl(var(--entity-postal))",
          'postal-bg': "hsl(var(--entity-postal-bg))",
          phone: "hsl(var(--entity-phone))",
          'phone-bg': "hsl(var(--entity-phone-bg))",
          email: "hsl(var(--entity-email))",
          'email-bg': "hsl(var(--entity-email-bg))",
          url: "hsl(var(--entity-url))",
          'url-bg': "hsl(var(--entity-url-bg))",
          ip: "hsl(var(--entity-ip))",
          'ip-bg': "hsl(var(--entity-ip-bg))",
          iban: "hsl(var(--entity-iban))",
          'iban-bg': "hsl(var(--entity-iban-bg))",
          bank: "hsl(var(--entity-bank))",
          'bank-bg': "hsl(var(--entity-bank-bg))",
          card: "hsl(var(--entity-card))",
          'card-bg': "hsl(var(--entity-card-bg))",
          social: "hsl(var(--entity-social))",
          'social-bg': "hsl(var(--entity-social-bg))",
          nss: "hsl(var(--entity-nss))",
          'nss-bg': "hsl(var(--entity-nss-bg))",
          license: "hsl(var(--entity-license))",
          'license-bg': "hsl(var(--entity-license-bg))",
          date: "hsl(var(--entity-date))",
          'date-bg': "hsl(var(--entity-date-bg))",
          medical: "hsl(var(--entity-medical))",
          'medical-bg': "hsl(var(--entity-medical-bg))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'Segoe UI', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'Consolas', 'monospace'],
      },
      fontSize: {
        'xs': '11px',
        'sm': '12px',
        'base': '13px',
        'lg': '14px',
        'xl': '16px',
        '2xl': '18px',
      },
    },
  },
  plugins: [],
};
